version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 7c4f35f96c482b8aa7547398c63bbf69
    secrets:
      - mongodb_password
    volumes:
      - mongo_prod_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bugacity-network
    ports:
      - "27017:27017"  # Для разработки - доступ к MongoDB

  # Application
  app:
    image: bugacity:latest
    ports:
      - "3001:3001"  # Для туннеля
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://bugacity_user:bugacity_password@bugacity_mongodb:27017/bugacity?authSource=bugacity
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      JWT_EXPIRES_IN: 7d
      MONGODB_PASSWORD_FILE: /run/secrets/mongodb_password
      SMTP_HOST: smtp.jino.ru
      SMTP_PORT: 465
      SMTP_USER: hello@gluko.city
      SMTP_PASS_FILE: /run/secrets/smtp_password
      VK_CLIENT_ID: 54075494
      VK_CLIENT_SECRET_FILE: /run/secrets/vk_secret
      YANDEX_CLIENT_ID: 03e35996472d40e3b0d980943e545cb8
      YANDEX_CLIENT_SECRET_FILE: /run/secrets/yandex_secret
      REACT_APP_API_URL: http://localhost:3001/api
    secrets:
      - jwt_secret
      - vk_secret
      - yandex_secret
      - smtp_password
      - mongodb_password
    depends_on:
      - mongodb
    networks:
      - bugacity-network
    volumes:
      - ./client/public:/app/client/public:ro

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - bugacity-network

secrets:
  jwt_secret:
    external: true
  vk_secret:
    external: true
  yandex_secret:
    external: true
  smtp_password:
    external: true
  mongodb_password:
    external: true

volumes:
  mongo_prod_data:
    external: true
    name: mongodb_data

networks:
  bugacity-network:
    driver: overlay
