events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Bugacity (этот стек)
    upstream app {
        server bugacity_app:3001;
    }

    # gluko: ./nginx/conf.d/  |  другие сайты: отдельные файлы в ./project.d/ (см. docker-compose)
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/project.d/*.conf;
}
